### ISSUE TITLE
CSS filter properties don't work

### ISSUE THREAD

**Issue by EwanRoycroft** [bbc/chromium#31]
There are a range of issue when using CSS `filter` properties. 

As seen in bbc/px-vod#36, `drop-shadow` results in corruption where the shadow should be. It seems that there may be some memory corruption, as the shadow will either be missing in parts, or some other image will be shown instead of the shadow.

The `blur` filter has also been tested. In this case, the blurred item does not appear on-screen.

**Comment by matt-hammond-001** [comment]
I believe this has now been fixed by https://github.com/bbc/px-yocto/issues/51
Please close if you agree @EwanRoycroft
