### ISSUE TITLE
Line on left-hand side of video content

### ISSUE THREAD

**Issue by EwanRoycroft** [bbc/chromium#35]
### Description
When playing videos in px-vod, there is a line on the left-hand size of the screen. The line is 1-2 pixels wide and is composed of content from elsewhere in the frame. The line does not appear on a Mac when playing from px-vod or in iPlayer, so is unique to the Pi. 

#### Screenshot
![IMG_2320](https://user-images.githubusercontent.com/2302279/145019646-bfb1feee-d28e-424b-808f-393f61afe13d.jpeg)

### More information
| Attribute | Value |
| --- | --- |
| **Branch** | `px-rpi-v89` |
| **Version** | 89.0.4389.72 |
| **Build** | Release |
| **Platform** | Ozone-DRM |
| **Target** | `chrome` |
| **Device** | Raspberry Pi 4B (4GB) |
| **OS** | px-yocto v0.0.13a |
| **Kernel** | 5.10.31-v7l |

### Steps to reproduce
Play a video using px-vod.
#### Command
```shell
/usr/lib/px-chromium/chrome --force-system-compositor-mode --disable-explicit-dma-fences --enable-gpu-rasterization --disable-seccomp-filter-sandbox --remote-debugging-port=9222 --kiosk http://localhost:8080/
```

**Comment by EwanRoycroft** [comment]
Things to test:
1. Does this happen if you play iPlayer on the Pi?
2. Does this happen if you play other video content on the Pi? (e.g. MP4 file) 
3. Does this happen on Raspbian?
4. Does this happen on Raspbian X11?

**Comment by EwanRoycroft** [comment]
I can't see this line any more. I have looked on my TV, my home monitor, and my office monitor.

@matt-hammond-001 can you confirm if you can see it on any of your screens?

**Comment by matt-hammond-001** [comment]
Confirmed I cannot see the line on the setup in the office. Will test at home tonight if useful.

**Comment by EwanRoycroft** [comment]
Please do, if you can't reproduce then I'll close.

**Comment by matt-hammond-001** [comment]
Confirmed, I'm not seeing it on my display at home either.

**Comment by matt-hammond-001** [comment]
Maybe the 64bit build has fixed it somehow.
