### ISSUE TITLE
Brief white flash when Chromium starts

### ISSUE THREAD

**Issue by EwanRoycroft** [bbc/chromium#37]
Despite closing #36, there is sometimes still a brief white flash when Chromium starts. [As noted in that thread](https://github.com/bbc/chromium/issues/36#issuecomment-1063168936), this is likely because either the Chromium application itself has a white background before the user agent stylesheet is loaded, or Chromium/Ozone fills the pixel buffer with white pixels when it first starts.

**Comment by matt-hammond-001** [comment]
No further ideas on how to address and only happens during boot up so rarely seen.
